import {
  ASSET_CATEGORIES
} from "./assetCategories";

import {
  ASSET_TYPES
} from "./assetTypes";

export const ASSET_REGISTRY = {

  [ASSET_TYPES.POLE]:
    ASSET_CATEGORIES.POLE,

  [ASSET_TYPES.FIBER]:
    ASSET_CATEGORIES.FIBER,

  [ASSET_TYPES.STATION]:
    ASSET_CATEGORIES.STATION,

  [ASSET_TYPES.RACK]:
    ASSET_CATEGORIES.RACK,

  [ASSET_TYPES.ACCESSORY]:
    ASSET_CATEGORIES.ACCESSORY,

  [ASSET_TYPES.OTDR]:
    ASSET_CATEGORIES.OTDR,

  [ASSET_TYPES.GROUP]:
    ASSET_CATEGORIES.GROUP

} as const;
