export const TREE_NODE_TYPES = {

  CATEGORY: "CATEGORY",

  ASSET: "ASSET",

  POSTES: "POSTES",

  CTOS: "CTOS",

  CEOS: "CEOS",

  CLIENTES: "CLIENTES",

  POSTES_CATEGORY: "POSTES_CATEGORY",

  FIBRAS_CATEGORY: "FIBRAS_CATEGORY",

  ESTACOES_CATEGORY: "ESTACOES_CATEGORY",

  RACKS_CATEGORY: "RACKS_CATEGORY",

  ACESSORIOS_CATEGORY: "ACESSORIOS_CATEGORY",

  OTDR_CATEGORY: "OTDR_CATEGORY",

  GRUPOS_CATEGORY: "GRUPOS_CATEGORY"

} as const;

export type TreeNodeType =
  typeof TREE_NODE_TYPES[keyof typeof TREE_NODE_TYPES];
